# Main context (this is the global configuration)
worker_processes 1;

events {
    worker_connections 1024;
}

http {
    # Upstream block to define the Node.js backend servers

    include mime.types;
    
    upstream nodejs_cluster {
        least_conn; # Load balancing method: least connections
        server app1:3000;
        server app2:3000;
        server app3:3000;
    }

    server {
        # Proxying requests to Node.js cluster
        listen 80;
        server_name myapp.local;

        return 301 https://$host$request_uri;

    }

    # HTTPS server
    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate     /etc/nginx/ssl/cert.pem;
        ssl_certificate_key /etc/nginx/ssl/key.pem;

        ssl_protocols TLSv1.2 TLSv1.3;

        # API → Node cluster (existing apps)
        location /api/ {
            proxy_pass http://nodejs_cluster/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Frontend → static files (served by nginx directly)
        location / {
            root /usr/share/nginx/html;
            index index.html;

             # SPA fallback (important for React/Vue)
            try_files $uri /index.html;
            }

        # Admin → separate container
        location /admin/ {
            proxy_pass http://admin_app:3000/;
            proxy_set_header Host $host;
        }       
    }   
}
