name: containerized-node-cluster-workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Security scan on code
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: json
          exit-code: 0
          vuln-type: os,library
          output: 'trivy-results.json'
      
      - name: Upload Trivy results
        uses: actions/upload-artifact@v3
        with:
          name: trivy-results
          path: trivy-results.json